CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    user_id UUID,
    guest_email VARCHAR(255),
    order_number VARCHAR(32) NOT NULL,
    status VARCHAR(30) DEFAULT 'pending',
    payment_status VARCHAR(30) DEFAULT 'unpaid',
    fulfillment_status VARCHAR(30) DEFAULT 'unfulfilled',
    currency VARCHAR(3) DEFAULT 'UZS',
    subtotal DECIMAL(14,2) NOT NULL,
    discount DECIMAL(14,2) DEFAULT 0,
    shipping_cost DECIMAL(14,2) DEFAULT 0,
    tax_total DECIMAL(14,2) DEFAULT 0,
    total DECIMAL(14,2) NOT NULL,
    coupon_code VARCHAR(50),
    shipping_address JSONB NOT NULL DEFAULT '{}',
    billing_address JSONB DEFAULT '{}',
    notes TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, order_number)
);
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    vendor_id UUID,
    product_id UUID NOT NULL,
    variant_id UUID,
    title VARCHAR(500) NOT NULL,
    sku VARCHAR(100),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(14,2) NOT NULL,
    total_price DECIMAL(14,2) NOT NULL,
    commission_rate DECIMAL(5,2) DEFAULT 0,
    commission_amount DECIMAL(14,2) DEFAULT 0,
    status VARCHAR(30) DEFAULT 'pending'
);
