package otelx

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
)

var (
	serviceNameCached string
	otlpEndpoint      string
	otlpOnce          sync.Once
)

// Init configures OTLP HTTP export when OTEL_EXPORTER_OTLP_ENDPOINT is set.
// Spans are always generated by Middleware (W3C traceparent) even without a collector.
func Init(serviceName string) (func(context.Context) error, error) {
	serviceNameCached = serviceName
	otlpOnce.Do(func() {
		otlpEndpoint = strings.TrimRight(strings.TrimSpace(os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT")), "/")
	})
	return func(context.Context) error { return nil }, nil
}

// Middleware injects/propagates W3C traceparent and optionally exports a span to OTLP.
func Middleware(serviceName string) gin.HandlerFunc {
	if serviceNameCached == "" {
		serviceNameCached = serviceName
	}
	return func(c *gin.Context) {
		traceID, spanID, parent := parseOrCreateTrace(c.GetHeader("traceparent"), c.GetHeader("X-Correlation-ID"))
		traceparent := fmt.Sprintf("00-%s-%s-01", traceID, spanID)
		c.Request.Header.Set("traceparent", traceparent)
		c.Header("traceparent", traceparent)
		c.Header("X-Trace-Id", traceID)
		c.Header("X-Service-Name", serviceName)
		c.Set("trace_id", traceID)
		c.Set("span_id", spanID)

		start := time.Now()
		c.Next()

		if otlpEndpoint != "" {
			go exportSpan(serviceName, traceID, spanID, parent, c.Request.Method, c.FullPath(), c.Writer.Status(), start)
		}
	}
}

func parseOrCreateTrace(traceparent, correlation string) (traceID, spanID, parentSpan string) {
	spanID = randomHex(8)
	if parts := strings.Split(strings.TrimSpace(traceparent), "-"); len(parts) >= 4 && len(parts[1]) == 32 {
		traceID = parts[1]
		parentSpan = parts[2]
		return traceID, spanID, parentSpan
	}
	if correlation != "" && len(correlation) >= 16 {
		// Derive a stable-ish trace id from correlation when present.
		h := make([]byte, 16)
		copy(h, []byte(correlation))
		traceID = hex.EncodeToString(h)
		if len(traceID) < 32 {
			traceID = (traceID + randomHex(16))[:32]
		}
		return traceID, spanID, ""
	}
	return randomHex(16), spanID, ""
}

func randomHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func exportSpan(service, traceID, spanID, parent, method, route string, status int, start time.Time) {
	if route == "" {
		route = "unknown"
	}
	end := time.Now()
	span := map[string]any{
		"traceId":           traceID,
		"spanId":            spanID,
		"name":              method + " " + route,
		"kind":              2, // SERVER
		"startTimeUnixNano": fmt.Sprintf("%d", start.UnixNano()),
		"endTimeUnixNano":   fmt.Sprintf("%d", end.UnixNano()),
		"attributes": []map[string]any{
			{"key": "http.method", "value": map[string]string{"stringValue": method}},
			{"key": "http.route", "value": map[string]string{"stringValue": route}},
			{"key": "http.status_code", "value": map[string]any{"intValue": status}},
			{"key": "service.name", "value": map[string]string{"stringValue": service}},
		},
	}
	if parent != "" {
		span["parentSpanId"] = parent
	}
	payload := map[string]any{
		"resourceSpans": []map[string]any{{
			"resource": map[string]any{
				"attributes": []map[string]any{
					{"key": "service.name", "value": map[string]string{"stringValue": service}},
				},
			},
			"scopeSpans": []map[string]any{{
				"spans": []map[string]any{span},
			}},
		}},
	}
	body, _ := json.Marshal(payload)
	endpoint := otlpEndpoint
	if !strings.Contains(endpoint, "/v1/traces") {
		endpoint += "/v1/traces"
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return
	}
	_ = resp.Body.Close()
}
